# This file configures the build and development settings for Netlify.

[build]
  command = "npm run build"
  functions = ".netlify/functions/"
  publish = "build/"

[dev]
  command = "npm start"
  port = 3005
  targetPort = 8888
  publish = "build"
  framework = "#custom"
